### ISSUE TITLE
Error: Regarding Loading Pre-Trained Weights

### ISSUE THREAD

**Issue by NaeemKhan333** [eriklindernoren/Action-Recognition#5]
I am using pre-trained weights which is given by you. But I am facing this problem.Please can you guide me to resolve this issue.Thank you

Namespace(channels=3, checkpoint_model='ConvLSTM_150.pth', dataset_path='data/UCF-101-frames', image_dim=224, latent_dim=512, video_path='1.mp4')
Traceback (most recent call last):
  File "test_on_video.py", line 49, in <module>
    model.load_state_dict(torch.load(opt.checkpoint_model))
  File "/home/naeem/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ConvLSTM:
Missing key(s) in state_dict: "lstm.lstm.weight_ih_l0_reverse", "lstm.lstm.weight_hh_l0_reverse", "lstm.lstm.bias_ih_l0_reverse", "lstm.lstm.bias_hh_l0_reverse", "lstm.output_layers.0.weight", "lstm.output_layers.0.bias", "lstm.output_layers.1.weight", "lstm.output_layers.1.bias", "lstm.output_layers.1.running_mean", "lstm.output_layers.1.running_var", "lstm.output_layers.3.weight", "lstm.output_layers.3.bias".
Unexpected key(s) in state_dict: "lstm.final.0.weight", "lstm.final.0.bias", "lstm.final.1.weight", "lstm.final.1.bias", "lstm.final.1.running_mean", "lstm.final.1.running_var", "lstm.final.1.num_batches_tracked", "lstm.final.3.weight", "lstm.final.3.bias".

**Comment by ridha95** [comment]
the same problem... any help

**Comment by shiwen1997** [comment]
the same problem... any help

**Comment by PRAN20** [comment]
the same problem.... any help
